steps:
  # 1️⃣ Install dependencies & run tests
  - name: python:3.10
    id: test
    entrypoint: bash
    env:
      - PYTHONPATH=.
    args:
      - -c
      - |
        pip install -r requirements.txt
        pytest

  # 2️⃣ Fetch SonarQube token from Secret Manager
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: fetch-sonar-token
    entrypoint: bash
    args:
      - -c
      - |
        gcloud secrets versions access latest \
          --secret=sonarqube-token > /workspace/sonar_token.txt

  # 3️⃣ Run SonarQube scan
  - name: sonarsource/sonar-scanner-cli
    id: sonar-scan
    entrypoint: bash
    args:
      - -c
      - |
        SONAR_TOKEN=$(cat /workspace/sonar_token.txt)

        sonar-scanner \
          -Dsonar.projectKey=gcp-devops \
          -Dsonar.projectName=gcp-devops \
          -Dsonar.projectBaseDir=/workspace \
          -Dsonar.sources=src \
          -Dsonar.tests=tests \
          -Dsonar.language=py \
          -Dsonar.python.version=3.10 \
          -Dsonar.scm.disabled=true \
          -Dsonar.userHome=/tmp \
          -Dsonar.working.directory=/tmp/.scannerwork \
          -Dsonar.host.url=http://10.10.2.2:9000 \
          -Dsonar.login=$$SONAR_TOKEN
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: projects/theena-devops/locations/asia-south1/workerPools/private-ci-pool
