# 2️⃣ Fetch SonarQube token
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  id: fetch-sonar-token
  entrypoint: bash
  args:
    - -c
    - |
      gcloud secrets versions access latest \
        --secret=sonarqube-token > /workspace/sonar_token.txt

# 3️⃣ SonarQube scan
- name: sonarsource/sonar-scanner-cli
  id: sonar-scan
  entrypoint: bash
  args:
    - -c
    - |
      SONAR_TOKEN=$(cat /workspace/sonar_token.txt)
      sonar-scanner \
        -Dsonar.projectKey=gcp-devops \
        -Dsonar.sources=src \
        -Dsonar.tests=tests \
        -Dsonar.python.version=3.10 \
        -Dsonar.host.url=http://10.10.2.2:9000 \
        -Dsonar.login=$$SONAR_TOKEN

